name: Sync to Gitee

on:
  push:                # 当 GitHub 有代码提交时触发同步
  schedule:
    - cron: '0 22 * * *' # 每天北京时间早上 6 点自动执行 (UTC 22:00)
  workflow_dispatch:   # 支持手动点击运行

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the GitHub repos to Gitee
        uses: Yikun/gitee-mirror-action@master
        with:
          # 你的 GitHub 用户名
          src: github/your_github_username
          # 你的 Gitee 用户名
          dst: gitee/your_gitee_username
          # 刚才在 Settings 里设置的变量名
          dst_key: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
          # 填入你想要同步的仓库名，多个用逗号隔开
          static_list: "ohmyzsh,zsh-autosuggestions,zsh-syntax-highlighting"
          force_update: true
          debug: true