name: Sync to Gitee

on:
  push:
  schedule:
    # 每天北京时间早上 6 点自动执行 (UTC 22:00)
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror with SSH
        uses: Yikun/gitee-mirror-action@master
        with:
          # 来源端：github/你的GitHub用户名
          src: github/renkx
          # 目的端：gitee/你的Gitee用户名
          dst: gitee/renkx
          # SSH 私钥，确保已经在 Gitee 设置了对应的公钥
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          # 填写你需要同步的三个仓库名，逗号隔开，不要有空格
          static_list: "ohmyzsh,zsh-autosuggestions,zsh-syntax-highlighting"
          # 强制同步
          force_update: true
          # 关键点：如果你的仓库是公开的，设置 clone_style 为 https 或 ssh
          clone_style: "ssh"